Created random functions
htmlacademy-javascript/1819879-keksobooking-24 pull request #3
Opened 2021-09-26 17:44 UTC by shestakov-rv

2021-09-26 19:22 UTC, ArbuAlex requested changes
Нужно исправить немного для соответствия требованиям

2021-09-26 19:22 UTC, ArbuAlex commented on js/main.js
> +function getRandomFloat(min, max, floatLength) {
точность в дальнейшем можно задать по дефолту

2021-09-26 19:22 UTC, ArbuAlex commented on js/main.js
> +    return null;
Я уже делал акцент здесь в прошлом потоке. Тут можно спорить о семантической реализации - функция в названии предполагает, что вернется некоторое int-значение, а вернется null, при этом работа скрипта продолжится. Собственно, здесь начинаются споры про ["null - ошибка на миллиард долларов".](https://vicdmitrienko.com/2017/08/18/the-billion-dollar-mistake/) Я бы либо выбрасывал исключение, либо возвращал min или max. Акцентирую внимание чисто для кругозора, необязательно к исправлению

2021-09-26 19:22 UTC, ArbuAlex commented on js/main.js
> +  const rand = Math.random() * (max - min) + min;
В условиях сказано, что интервал должет быть от 0

2021-09-28 19:33 UTC, shestakov-rv commented on js/main.js
> +  const rand = Math.random() * (max - min) + min;
Не понял вопроса)
Судя по тексту, имеется ввиду что на входе ожидаются только положительные числа, включая ноль.
_Учтите, что диапазон может быть только положительный, включая ноль._
Нужно обрабатывать все таки отрицательные числа на входе?

2021-09-28 19:40 UTC, shestakov-rv commented on js/main.js
> +function getRandomFloat(min, max, floatLength) {
Не понял, что нужно сдлеать?

2021-09-28 19:41 UTC, shestakov-rv commented on js/main.js
> +    return null;
Буду возвращать min

2021-09-28 20:26 UTC, ArbuAlex commented on js/main.js
> +function getRandomFloat(min, max, floatLength) {
floatLength = 2

2021-09-28 20:48 UTC, shestakov-rv commented on js/main.js
> +function getRandomFloat(min, max, floatLength) {
Ок, принял)

2021-09-28 21:28 UTC, merged